//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace subarashi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblArabalar
    {
        public int id { get; set; }
        public string marka { get; set; }
        public string model { get; set; }
        public string modelyili { get; set; }
        public Nullable<double> fiyati { get; set; }
    }
}
